# Generated by Django 6.0.6 on 2026-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='order',
            name='tx_ref',
            field=models.CharField(default='migration-default', max_length=266, unique=True),
            preserve_default=False,
        ),
    ]
