# Generated by Django 6.0.6 on 2026-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='addresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
