# Generated by Django 6.0.6 on 2026-07-08 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('user_blocked', 'User Blocked'), ('user_unblocked', 'User Unblocked'), ('role_changed', 'Role Changed'), ('password_reset', 'Password Reset'), ('customer_approved', 'Customer Approved'), ('customer_rejected', 'Customer Rejected'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deactivated', 'Product Deactivated'), ('product_reactivated', 'Product Reactivated'), ('category_created', 'Category Created'), ('category_updated', 'Category Updated'), ('category_deleted', 'Category Deleted'), ('settings_updated', 'Store Settings Updated'), ('order_status_changed', 'Order Status Changed'), ('login', 'User Login'), ('logout', 'User Logout')], db_index=True, max_length=50)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='custom_admi_actor_i_b5a53e_idx'), models.Index(fields=['action', '-timestamp'], name='custom_admi_action_7b2581_idx')],
            },
        ),
    ]
